server:
  port: 80
  servlet:
    session:
      timeout: 60m
spring:
  oauth2:
    client:
      registration:
        google:
          client-id: 360163877109-edolvlg3hc3lj6u71p4p8d12mp2g6ktt.apps.googleusercontent.com
          client-secret: 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
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope: openid, profile, email
        github:
          client-id: Ov23lieZCLULxhkty6ev
          client-secret: 38b8505ea09fbdde8e261e04d3c9460640095709
          scope: read:user
          user-name-attribute: login
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          user-name-attribute: sub
        github:
          authorization-uri: https://github.com/login/oauth/authorize
          token-uri: https://github.com/login/oauth/access_token
          user-info-uri: https://api.github.com/user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #47.99.126.109 3Gt7*p  localhost root
    url: jdbc:mysql://47.99.126.109:3306/chatman?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mhchat773584..
  rabbitmq:
    host: 49.235.137.135
    port: 5672
    username: muhuo
    password: muhuo
    virtual-host: /
  redis:
    host: 47.99.126.109
    port: 6379
  application:
    name: gpt_user
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决spring boot2.7.x与swagger2的冲突问题
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    mode: HTML5
#邮箱smtp服务器
mail:
  user: mhchat@ttzi.top
  password: T1e2s3t4P5a6s
  mime:
    splitlongparameters: false  #用于解决附件名过长导致的显示异常
  smtp:
    host: smtpdm.aliyun.com
    port: 465
    auth: true
    from: mhchat@ttzi.top
    ssl:
      enable: true
    #qq邮箱授权码  YPENGGTGDQQHAZLJ    mhchatal@qq.com  kiexyairjfkvbgii

    fromEmail: mhchat@ttzi.top
    fromName: 木火科技
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:  #缩略图生成参数
    width: 150
    height: 150
  tracker-list:   #TrackerList参数,支持多个
    - ttzi.top:22122
pandora:
  config:
    file: D:\\GameDo\\tokens.json
#    file: /opt  #docker容器内部挂载文件

base:
  url: https://ttzi.top/
token:
  share:
    uri: /api/token/register
  access:
    uri: /api/auth/login
  proxy_api_prefix: mhchat3464
app:
  config:
    url: https://ngedlktfticp.cloud.sealos.io
    talk: /v1/chat/completions
    apiKey: sk-8nlPkajFRjJjizyy2bBfA8043f294b5982B7D867D2D95d8d
logging:
  level:
    org:
      springframework:
        security: DEBUG
